name: Sync Upstream Repository

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6:00 UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: https://github.com/ORIGINAL_OWNER/UPSTREAM_REPO_NAME.git
          upstream_branch: main  # Optional; can be omitted if using 'main'
          downstream_branch: main  # Optional; can be omitted if using 'main'
          token: ${{ secrets.GITHUB_TOKEN }}
